version: '3'

# docker-compose up --build
# uvicorn main:app --host 0.0.0.0 --port 8000 --reload
services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: python server.py
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    healthcheck:
      test: curl -f http://localhost:8000
      interval: 60s
      timeout: 3s
      retries: 1
    networks:
      - server

  mongo:
    image: mongo:latest
    user: root
    ports:
      - "27017:27017"
    command: mongod
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwer1234!@
    networks:
      - server
    depends_on:
      - fastapi

  redis:
    image: redis:latest
    restart: on-failure
    command: redis-server
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - server
    depends_on:
      - fastapi
    

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    networks:
      - server

volumes:
  mongo-data:
  redis-data:

networks:
  server:
